# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2017-04-30 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_remove_shop_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='logo',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
