# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 13:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_shop_indeed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='indeed',
        ),
    ]
